.add({ duration: 300, easing: 'easeOutCirc', targets: '.logo-ac-text', translateY: '-200px' })
.add({ easing: 'easeOutBounce', targets: '.logo-ac-text', translateY: '0px' })
.add({ duration: 130, easing: 'easeOutQuart', targets: '.logo-ac-accent', color: '#ffffff' }, 1000)
.add({ easing: 'easeOutElastic', targets: '.logo-ac-text', fontSize: '70px' }, 800)
.add({ easing: 'easeOutExpo', targets: '.logo-spliter', height: '100%' })
.add({ duration: 300, targets: '.branding', opacity: 0 })